apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qvhoff7r3-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/qvhoff7r3-dotnet-basic-gitops